config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome', to: 'welcome#index'
  root 'welcome#index'

  resources :sessions, only:[:new,:create]
  resources :users, only:[:new,:create,:destroy,:show]
  resources :parents, except:[:destroy]
  resources :students, except:[:destroy]
  resources :reports, except:[:destroy,:create]

  resources :students, only:[:create] do
    resources :reports
  end
  delete '/reports/:id', to: 'reports#destroy'
  delete '/students/:id', to:'students#destroy'
  delete '/parents/:id', to:'parents#destroy'
  delete '/logout', to:'sessions#destroy'
end

#   Prefix Verb   URI Pattern                  Controller#Action
#      welcome GET    /welcome(.:format)           welcome#index
#         root GET    /                            welcome#index
#     sessions POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user GET    /users/:id(.:format)         users#show
#              DELETE /users/:id(.:format)         users#destroy
#      parents GET    /parents(.:format)           parents#index
#              POST   /parents(.:format)           parents#create
#   new_parent GET    /parents/new(.:format)       parents#new
#  edit_parent GET    /parents/:id/edit(.:format)  parents#edit
#       parent GET    /parents/:id(.:format)       parents#show
#              PATCH  /parents/:id(.:format)       parents#update
#              PUT    /parents/:id(.:format)       parents#update
#     students GET    /students(.:format)          students#index
#              POST   /students(.:format)          students#create
#  new_student GET    /students/new(.:format)      students#new
# edit_student GET    /students/:id/edit(.:format) students#edit
#      student GET    /students/:id(.:format)      students#show
#              PATCH  /students/:id(.:format)      students#update
#              PUT    /students/:id(.:format)      students#update
#      reports GET    /reports(.:format)           reports#index
#              POST   /reports(.:format)           reports#create
#   new_report GET    /reports/new(.:format)       reports#new
#  edit_report GET    /reports/:id/edit(.:format)  reports#edit
#       report GET    /reports/:id(.:format)       reports#show
#              PATCH  /reports/:id(.:format)       reports#update
#              PUT    /reports/:id(.:format)       reports#update
#              DELETE /reports/:id(.:format)       reports#destroy
#              DELETE /students/:id(.:format)      students#destroy
#              DELETE /parents/:id(.:format)       parents#destroy
      # logout DELETE /logout(.:format)            sessions#destroy

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :last_name,
  :teacher_id, presence:true

  belongs_to :teacher, class_name: :User

  belongs_to :parent
  has_many :reports, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include SessionsHelper
  before_action :secure_route
  def index
      @students = Student.where(teacher_id:current_user).order(:first_name)
    if @students.nil?
      redirect_to '/students/new'
    end
  end

  def new
    @parents = Parent.where(teacher_id:current_user).order(:first_name)
    @student = Student.new
  end

  def create
    space = params[:parent].index(" ")
    first_name = params[:parent][0..space-1]
    last_name = params[:parent][space+1..-1]

    @student = Student.new(
      first_name:params[:student][:first_name],
      last_name:params[:student][:last_name],
      teacher_id: current_user.id,
      parent_id: Parent.find_by(first_name:first_name, last_name:last_name).id
    )
    if @student.save
      redirect_to students_path
    else
      @errors = @student.errors
      render 'new'
    end
  end

  def show
    @reports= Report.where(student_id:params[:id]).order('created_at DESC')
    @student = Student.find_by(id:params[:id])
  end

  def edit
    @parents = Parent.where(teacher_id:current_user.id).order(:last_name)
    @student = Student.find_by(id:params[:id])
  end

  def update
    space = params[:parent].index(" ")
    first_name = params[:parent][0..space-1]
    last_name = params[:parent][space+1..-1]
    @student= Student.find_by(id:params[:id])
    if @student.update(
                        first_name:params[:student][:first_name],
                        last_name:params[:student][:last_name],
                        parent_id: Parent.find_by(first_name:first_name, last_name:last_name).id
                      )
      redirect_to '/students'
    else
      render 'edit'
    end
  end

  def destroy
    student = Student.find_by(id:params[:id]).destroy
    redirect_to '/students'
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, html:{class:'form-signin'} do |f| %>
  <% if @student.save === false %>
    <h2 class="form-signin-heading">Add Student</h2>
  <% else %>
    <h2 class="form-signin-heading">Edit Student</h2>
  <% end %>


  <%= f.label :first_name,class:"sr-only" %>
  <%= f.text_field :first_name,class:'form-control', placeholder: "First Name" %>

  <%= f.label :last_name,class:"sr-only" %>
  <%= f.text_field :last_name,class:'form-control', placeholder: "Last Name" %>
  <h4 class="form-signin-heading">Who is the Mom/Dad?</h4>
  <% parents = @parents.map { |parent| [parent.first_name + " " + parent.last_name] } %>
  <%= select_tag(:parent, options_for_select(parents) ) %>
  <%= f.submit 'Submit',class:'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/students/index.html.erb
<div class="right-container">
  <h1>Students</h1>
  <h4><%= link_to "Add a Student", new_student_path, class:'add-student' %></h4>
  <div class="student-container">
    <% @students.each do |student| %>
      <div class="pretty-report student bg-image">
        <h5><%= student.first_name.capitalize + " " + student.last_name[0]+"."%></h5>
          <%= link_to "Edit", "/students/#{student.id}/edit", class:"link" %> |
          <%= link_to "Delete", "/students/#{student.id}", method: 'delete',data: {confirm: "Deleting this student will erase all of his/her reports. Are you sure?"}, class:"link" %> |
          <%= link_to "View Reports", "/students/#{student.id}",class:"link" %> |
          <%= link_to "Add Report", "/students/#{student.id}/reports/new",class:"link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<div class="right-container">
  <div class="login">
    <% if @parents.count > 0 %>
      <%= render 'form' %>
    <% else %>
      <h1>Please add Parents first <%= link_to 'here', '/parents/new'%></h1>
    <% end %>
    <% if @errors %>
      <% @errors.each do |msg| %>
        <div class="errors">
          <p><%= msg %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<div class="right-container">
  <h1><%= @student.first_name.capitalize %>'s Reports</h1>
  <h4><% if @reports.empty? %>
    <%= link_to 'add new report', students_path %>
  <% end %></h4>
  <%@reports.each do |report|%>
  <div class="report-container pretty-report bg-image">
    <h2><%= report.student.first_name + " " + report.student.last_name[0] + "."  %></h2>
    <h5>Grade: <%= Report.grade(report.id).floor %> %</h5>
    <h5><%= report.assignment %></h2>
    <h6><%= Report.date(report.id) %></h6>
    <%= link_to "view report", "/reports/#{report.id}" %>
  </div>
    <% end %>
</div>