config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome', to: 'welcome#index'
  root 'welcome#index'

  resources :sessions, only:[:new,:create]
  resources :users, only:[:new,:create,:destroy,:show]
  resources :parents, except:[:destroy]
  resources :students, except:[:destroy]
  resources :reports, except:[:destroy,:create]

  resources :students, only:[:create] do
    resources :reports
  end
  delete '/reports/:id', to: 'reports#destroy'
  delete '/students/:id', to:'students#destroy'
  delete '/parents/:id', to:'parents#destroy'
  delete '/logout', to:'sessions#destroy'
end

#   Prefix Verb   URI Pattern                  Controller#Action
#      welcome GET    /welcome(.:format)           welcome#index
#         root GET    /                            welcome#index
#     sessions POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user GET    /users/:id(.:format)         users#show
#              DELETE /users/:id(.:format)         users#destroy
#      parents GET    /parents(.:format)           parents#index
#              POST   /parents(.:format)           parents#create
#   new_parent GET    /parents/new(.:format)       parents#new
#  edit_parent GET    /parents/:id/edit(.:format)  parents#edit
#       parent GET    /parents/:id(.:format)       parents#show
#              PATCH  /parents/:id(.:format)       parents#update
#              PUT    /parents/:id(.:format)       parents#update
#     students GET    /students(.:format)          students#index
#              POST   /students(.:format)          students#create
#  new_student GET    /students/new(.:format)      students#new
# edit_student GET    /students/:id/edit(.:format) students#edit
#      student GET    /students/:id(.:format)      students#show
#              PATCH  /students/:id(.:format)      students#update
#              PUT    /students/:id(.:format)      students#update
#      reports GET    /reports(.:format)           reports#index
#              POST   /reports(.:format)           reports#create
#   new_report GET    /reports/new(.:format)       reports#new
#  edit_report GET    /reports/:id/edit(.:format)  reports#edit
#       report GET    /reports/:id(.:format)       reports#show
#              PATCH  /reports/:id(.:format)       reports#update
#              PUT    /reports/:id(.:format)       reports#update
#              DELETE /reports/:id(.:format)       reports#destroy
#              DELETE /students/:id(.:format)      students#destroy
#              DELETE /parents/:id(.:format)       parents#destroy
      # logout DELETE /logout(.:format)            sessions#destroy

app/models/parent.rb
class Parent < ApplicationRecord
  validates :first_name, :last_name, :email, :teacher_id, presence:true
  validates :email, uniqueness:true
  has_many :children, foreign_key: :parent_id, class_name: :Student
  belongs_to :teacher, class_name: :User
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  include SessionsHelper
  before_action :secure_route
  def index
    @parents = Parent.where(teacher_id:current_user).order(:first_name)
    if @parents.nil?
      redirect_to '/parents/new'
    end
  end

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.new(
      first_name:params[:parent][:first_name],
      last_name:params[:parent][:last_name],
      email: params[:parent][:email],
      teacher_id: current_user.id
    )
    if @parent.save
      redirect_to parents_path
    else
      @errors = @parent.errors
      render 'new'
    end
  end

  def show

  end

  def edit
    @parent = Parent.find_by(id:params[:id])
  end

  def update
    @parent= Parent.find_by(id:params[:id])
    if @parent.update(
                        first_name:params[:parent][:first_name],
                        last_name:params[:parent][:last_name],
                        email:params[:parent][:email]
                      )
      redirect_to '/parents'
    else
      render 'edit'
    end
  end

  def destroy
    Parent.find_by(id:params[:id]).destroy
    redirect_to '/parents'
  end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.erb
<%= form_for @parent, html:{class:'form-signin'} do |f| %>
  <% if @parent.save === false %>
    <h2 class="form-signin-heading">Add Parent</h2>
  <% else %>
    <h2 class="form-signin-heading">Edit Parent</h2>
  <% end %>

  <%= f.label :first_name,class:"sr-only" %>
  <%= f.text_field :first_name,class:'form-control', placeholder: "First Name" %>

  <%= f.label :last_name,class:"sr-only" %>
  <%= f.text_field :last_name,class:'form-control', placeholder: "Last Name" %>

  <%= f.email_field :email, id:'inputEmail',class:'form-control', placeholder: "Email address" %>

  <%= f.submit 'Submit',class:'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/parents/edit.html.erb
<div class="right-container">
  <div class="login">
    <%= render 'form' %>
    <% if @errors %>
      <% @errors.each do |msg| %>
        <div class="errors">
          <p><%= msg %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/parents/index.html.erb
<div class="right-container">
  <h1>Parents</h1>
  <h4><%= link_to "Add a Parent", new_parent_path, class:'add-student' %></h4>
  <% if !@parents.empty? %>
    <p class="note"> <b>NOTE</b>: Once a student is added, he/she will appear under corresponding parents name. </p>
  <% end %>
  <div class="student-container">
    <% @parents.each do |parent| %>
      <div class="pretty-report center bg-image">
        <h5><%= parent.first_name.capitalize + " " + parent.last_name[0]+"."%></h5>
            <% parent.children.each do |child| %>
              <div><%= link_to child.first_name.capitalize, "/students/#{child.id}", class:"p-s-name" %></div>
            <% end %>
            <%= link_to "Edit", "/parents/#{parent.id}/edit", class:"link"%> |
            <%= link_to "Delete", "/parents/#{parent.id}", method: 'delete',data: {confirm: " Are you sure?"},class:"link" %>

      </div>
    <% end %>
  </div>
</div>

app/views/parents/new.html.erb
<div class="right-container">
  <div class="login">
    <%= render 'form' %>
    <% if @errors %>
      <% @errors.each do |msg| %>
        <div class="errors">
          <p><%= msg %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>