config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome', to: 'welcome#index'
  root 'welcome#index'

  resources :sessions, only:[:new,:create]
  resources :users, only:[:new,:create,:destroy,:show]
  resources :parents, except:[:destroy]
  resources :students, except:[:destroy]
  resources :reports, except:[:destroy,:create]

  resources :students, only:[:create] do
    resources :reports
  end
  delete '/reports/:id', to: 'reports#destroy'
  delete '/students/:id', to:'students#destroy'
  delete '/parents/:id', to:'parents#destroy'
  delete '/logout', to:'sessions#destroy'
end

#   Prefix Verb   URI Pattern                  Controller#Action
#      welcome GET    /welcome(.:format)           welcome#index
#         root GET    /                            welcome#index
#     sessions POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user GET    /users/:id(.:format)         users#show
#              DELETE /users/:id(.:format)         users#destroy
#      parents GET    /parents(.:format)           parents#index
#              POST   /parents(.:format)           parents#create
#   new_parent GET    /parents/new(.:format)       parents#new
#  edit_parent GET    /parents/:id/edit(.:format)  parents#edit
#       parent GET    /parents/:id(.:format)       parents#show
#              PATCH  /parents/:id(.:format)       parents#update
#              PUT    /parents/:id(.:format)       parents#update
#     students GET    /students(.:format)          students#index
#              POST   /students(.:format)          students#create
#  new_student GET    /students/new(.:format)      students#new
# edit_student GET    /students/:id/edit(.:format) students#edit
#      student GET    /students/:id(.:format)      students#show
#              PATCH  /students/:id(.:format)      students#update
#              PUT    /students/:id(.:format)      students#update
#      reports GET    /reports(.:format)           reports#index
#              POST   /reports(.:format)           reports#create
#   new_report GET    /reports/new(.:format)       reports#new
#  edit_report GET    /reports/:id/edit(.:format)  reports#edit
#       report GET    /reports/:id(.:format)       reports#show
#              PATCH  /reports/:id(.:format)       reports#update
#              PUT    /reports/:id(.:format)       reports#update
#              DELETE /reports/:id(.:format)       reports#destroy
#              DELETE /students/:id(.:format)      students#destroy
#              DELETE /parents/:id(.:format)       parents#destroy
      # logout DELETE /logout(.:format)            sessions#destroy

app/models/report.rb
class Report < ApplicationRecord
  validates :test_quizes,:homework,:classwork,:punctuality_attendance,:contributions,:collab_coop, numericality:{only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11}, presence: true
  validates :openness_to_feedback,:takes_responsibility, numericality:{only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}, presence: true
  validates :consistently_good_effort, numericality:{only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 14}, presence: true
  validates :teacher_id, :student_id, presence: true
  validates :assignment, presence:true

  belongs_to :teacher, class_name: :User
  belongs_to :student

  def self.performance_score(report_id)
    report = self.find_by(id:report_id)
    return report.test_quizes+report.homework + report.classwork
  end

  def self.participation_score(report_id)
    report = self.find_by(id:report_id)
    return report.punctuality_attendance + report.contributions + report.collab_coop
  end

  def self.commitment_score(report_id)
    report = self.find_by(id:report_id)
    return report.openness_to_feedback + report.consistently_good_effort + report.takes_responsibility
  end

  def self.total_score(report_id)
    Report.performance_score(report_id) + Report.participation_score(report_id) + Report.commitment_score(report_id)
  end

  def self.performance_total_score
    return 33
  end

  def self.participation_total_score
    return 33
  end

  def self.commitment_total_score
    return 34
  end

  def self.grade(report_id)
    one_hundred = Report.performance_total_score + Report.participation_total_score + Report.commitment_total_score
    percentage = self.total_score(report_id)/one_hundred.to_f
    return (percentage * 100).floor
  end

  def self.date(report_id)
    self.find_by(id:report_id).created_at.strftime("%A, %m/%d/%Y")
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include SessionsHelper
  before_action :secure_route

  def index
    @reports = Report.where(teacher_id:current_user).order('created_at desc')
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(
                          test_quizes:params[:report][:test_quizes].to_i,
                          homework:params[:report][:homework].to_i,
                          classwork:params[:report][:classwork].to_i,
                          punctuality_attendance:params[:report][:punctuality_attendance].to_i,
                          contributions:params[:report][:contributions].to_i,
                          collab_coop:params[:report][:collab_coop].to_i,
                          openness_to_feedback:params[:report][:openness_to_feedback].to_i,
                          consistently_good_effort:params[:report][:consistently_good_effort].to_i,
                          takes_responsibility:params[:report][:takes_responsibility].to_i,
                          teacher_id:current_user.id,
                          student_id:params[:student_id].to_i,
                          feedback:params[:report][:feedback],
                          assignment:params[:report][:assignment]
                        )
    if @report.save
      redirect_to "/students/#{params[:student_id].to_i}"
    else
      @errors = @report.errors.full_messages
      render 'new'
    end
  end

  def edit
    @report = Report.find_by(id:params[:id])
  end

  def update
    @report = Report.find_by(id:params[:id])
    if @report.update(
                          test_quizes:params[:report][:test_quizes].to_i,
                          homework:params[:report][:homework].to_i,
                          classwork:params[:report][:classwork].to_i,
                          punctuality_attendance:params[:report][:punctuality_attendance].to_i,
                          contributions:params[:report][:contributions].to_i,
                          collab_coop:params[:report][:collab_coop].to_i,
                          openness_to_feedback:params[:report][:openness_to_feedback].to_i,
                          consistently_good_effort:params[:report][:consistently_good_effort].to_i,
                          takes_responsibility:params[:report][:takes_responsibility].to_i,
                          teacher_id:current_user.id,
                          student_id:Report.find_by(id:params[:id]).student.id,
                          feedback:params[:report][:feedback],
                          assignment:params[:report][:assignment]
                        )
      render 'show'
    else
      @errors = @report.errors.full_messages
      render 'edit'
    end
  end


  def show
    @report=Report.find_by(id:params[:id])
  end

  def destroy
    Report.find_by(id:params[:id]).destroy
    redirect_to '/reports'
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
 <%= form_for @report, url: {action: "create"}, class:'form-signin' do |f| %>
    <% if @errors %>
        <% @errors.each do |msg| %>
          <div class="errors">
            <p><%= msg %></p>
          </div>
        <% end %>
    <% end %>

    <div class="performance small-form">
      <h5>Performance</h5>
      <div class="fields">
        <%= f.label "Test + Quizes" %>
        <%= f.text_field :test_quizes,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Homework" %>
        <%= f.text_field :homework,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Classwork" %>
        <%= f.text_field :classwork,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="participation small-form">
      <h5>Participation</h5>
      <div class="fields">
        <%= f.label "Punctuality + Attendance" %>
        <%= f.text_field :punctuality_attendance,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Contributions" %>
        <%= f.text_field :contributions,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Collab + Coop" %>
        <%= f.text_field :collab_coop,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="commitment small-form">
      <h5>Commitment</h5>
      <div class="fields">
        <%= f.label "Openness to Feedback" %>
        <%= f.text_field :openness_to_feedback,class:'form-control', placeholder: "(0-10)" %>

        <%= f.label "Consistently Good Effort" %>
        <%= f.text_field :consistently_good_effort,class:'form-control', placeholder: "(0-14)" %>

        <%= f.label "Takes Responsibility" %>
        <%= f.text_field :takes_responsibility,class:'form-control', placeholder: "(0-10)" %>
      </div>
    </div>

    <div class="feedback small-form">
      <div class="fields">
        <%= f.text_area :feedback,class:'form-control', placeholder: "Feedback" %>
        <%= f.text_field :assignment,class:'form-control', placeholder: "Assignment Name" %>
      </div>
    </div>

    <div class="">
      <%= f.submit 'Submit',class:'btn btn-lg btn-primary btn-block' %>
    </div>

    <% end %>

app/views/reports/edit.html.erb
<div class="right-container">
  <div class="login">
    <h1>Edit Report</h1>
    <% if @errors %>
        <% @errors.each do |msg| %>
          <div class="errors">
            <p><%= msg %></p>
          </div>
        <% end %>
    <% end %>
    <%= form_for @report, url: {action: "update"}, class:'form-signin' do |f| %>

    <div class="performance pretty-report bg-image">
      <h5>Performance</h5>
      <div class="fields">
        <%= f.label "Test + Quizes" %>
        <%= f.text_field :test_quizes,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Homework" %>
        <%= f.text_field :homework,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Classwork" %>
        <%= f.text_field :classwork,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="participation pretty-report bg-image">
      <h5>Participation</h5>
      <div class="fields">
        <%= f.label "Punctuality + Attendance" %>
        <%= f.text_field :punctuality_attendance,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Contributions" %>
        <%= f.text_field :contributions,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Collab + Coop" %>
        <%= f.text_field :collab_coop,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="commitment pretty-report bg-image">
      <h5>Commitment</h5>
      <div class="fields">
        <%= f.label "Openness to Feedback" %>
        <%= f.text_field :openness_to_feedback,class:'form-control', placeholder: "(0-10)" %>

        <%= f.label "Consistently Good Effort" %>
        <%= f.text_field :consistently_good_effort,class:'form-control', placeholder: "(0-14)" %>

        <%= f.label "Takes Responsibility" %>
        <%= f.text_field :takes_responsibility,class:'form-control', placeholder: "(0-10)" %>
      </div>
    </div>

    <div class="feed pretty-report bg-image">
      <div class="fields">
        <%= f.text_area :feedback,class:'form-control', placeholder: "Feedback" %>
        <%= f.text_field :assignment,class:'form-control', placeholder: "Assignment Name" %>
      </div>
    </div>

    <%= f.submit 'Submit',class:'btn btn-lg btn-primary btn-block submit' %>

    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<div class="right-container">
  <h1>All Reports</h1>
  <h4><% if @reports.empty? %>
    <%= link_to 'add new report', students_path %>
  <% end %></h4>
  <%@reports.each do |report|%>
  <div class="report-container pretty-report bg-image">
    <h2><%= report.student.first_name + " " + report.student.last_name[0] + "."  %></h2>
    <h5>Grade: <%= Report.grade(report.id).floor %> %</h5>
    <h5><%= report.assignment %></h2>
    <h6><%= Report.date(report.id) %></h6>
    <%= link_to "view report", "/reports/#{report.id}" %>
  </div>
    <% end %>
</div>

app/views/reports/new.html.erb
<div class="right-container">
  <div class="login">
    <h1>New Report</h1>
    <%= form_for @report, url: {action: "create"}, class:'form-signin' do |f| %>
    <% if @errors %>
        <% @errors.each do |msg| %>
          <div class="errors">
            <p><%= msg %></p>
          </div>
        <% end %>
    <% end %>

    <div class="performance pretty-report bg-image">
      <h5>Performance</h5>
      <div class="fields">
        <%= f.label "Test + Quizes" %>
        <%= f.text_field :test_quizes,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Homework" %>
        <%= f.text_field :homework,class:'form-control', placeholder: "(0-11)" %>
        <%= f.label "Classwork" %>
        <%= f.text_field :classwork,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="participation pretty-report bg-image">
      <h5>Participation</h5>
      <div class="fields">
        <%= f.label "Punctuality + Attendance" %>
        <%= f.text_field :punctuality_attendance,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Contributions" %>
        <%= f.text_field :contributions,class:'form-control', placeholder: "(0-11)" %>

        <%= f.label "Collab + Coop" %>
        <%= f.text_field :collab_coop,class:'form-control', placeholder: "(0-11)" %>
      </div>
    </div>

    <div class="commitment pretty-report bg-image">
      <h5>Commitment</h5>
      <div class="fields">
        <%= f.label "Openness to Feedback" %>
        <%= f.text_field :openness_to_feedback,class:'form-control', placeholder: "(0-10)" %>

        <%= f.label "Consistently Good Effort" %>
        <%= f.text_field :consistently_good_effort,class:'form-control', placeholder: "(0-14)" %>

        <%= f.label "Takes Responsibility" %>
        <%= f.text_field :takes_responsibility,class:'form-control', placeholder: "(0-10)" %>
      </div>
    </div>

    <div class="pretty-report bg-image">
      <div class="fields feedback">
        <%= f.text_area :feedback,class:'form-control', placeholder: "Feedback" %>
        <%= f.text_field :assignment,class:'form-control', placeholder: "Assignment Name" %>
      </div>
    </div>
    <%= f.submit 'Submit',class:'btn btn-lg btn-primary btn-block submit' %>

    <% end %>

  </div>
</div>

<!-- # :test_quizes,
# :homework,
# :classwork,
# :punctuality_attendance,
# :contributions,
# :collab_coop,
# :openness_to_feedback,
# :consistently_good_effort,
# :takes_responsibility,
# :teacher_id,
# :student_id,
# :feedback,
# :assignment,
# :date -->

app/views/reports/show.html.erb
<div class="right-container">
  <div class="login">
    <h1><%= @report.student.first_name.capitalize %>'s Report</h1>
    <h4><%= link_to "Delete", "/reports/#{@report.id}",method: 'delete',data: {confirm: "Are you sure you want to delete this report?"} %></h4>
    <h4><%= link_to "Edit Report", edit_report_path %></h4>
    <h3>Assignment: <%= @report.assignment %></h3>
    <h3><%= Report.date(@report.id) %></h3>
    <h3>Grade: <%= Report.grade(@report.id)%> %</h3>

    <div class="pretty-report bg-image">
      <h4>Performance</h4>
      <h5>(<%= Report.performance_score(@report.id) %> out of <%= Report.performance_total_score %> )</h5>
      <li>Skill Improvement (Tests + Quizes): <%= @report.test_quizes %>/11</li>
      <li>Homework: <%= @report.homework %>/11</li>
      <li>Classwork: <%= @report.classwork %>/11</li>
    </div>
    <div class="pretty-report bg-image">
      <h4>Participation</h4>
      <h5>(<%= Report.participation_score(@report.id) %> out of <%= Report.participation_total_score %>)</h5>
      <li>Punctuality + Attendance: <%= @report.punctuality_attendance %>/11</li>
      <li>Contributions: <%= @report.contributions %>/11</li>
      <li>Collaboration + Cooperation: <%= @report.collab_coop %>/11</li>
    </div>
    <div class="pretty-report bg-image">
      <h4>Commitment</h4>
      <h5>(<%= Report.commitment_score(@report.id) %> out of <%= Report.commitment_total_score %>)</h5>
      <li>Openness to feedback: <%= @report.openness_to_feedback %>/10</li>
      <li>Consistently Good Effort: <%= @report.consistently_good_effort %>/14</li>
      <li>Takes Responsibility: <%= @report.takes_responsibility %>/10</li>
    </div>

    <div class="pretty-report bg-image feed">
      <h4>Feedback</h4>
      <p><%= @report.feedback %></p>
    </div>
  </div>
</div>