config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome', to: 'welcome#index'
  root 'welcome#index'

  resources :sessions, only:[:new,:create]
  resources :users, only:[:new,:create,:destroy,:show]
  resources :parents, except:[:destroy]
  resources :students, except:[:destroy]
  resources :reports, except:[:destroy,:create]

  resources :students, only:[:create] do
    resources :reports
  end
  delete '/reports/:id', to: 'reports#destroy'
  delete '/students/:id', to:'students#destroy'
  delete '/parents/:id', to:'parents#destroy'
  delete '/logout', to:'sessions#destroy'
end

#   Prefix Verb   URI Pattern                  Controller#Action
#      welcome GET    /welcome(.:format)           welcome#index
#         root GET    /                            welcome#index
#     sessions POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user GET    /users/:id(.:format)         users#show
#              DELETE /users/:id(.:format)         users#destroy
#      parents GET    /parents(.:format)           parents#index
#              POST   /parents(.:format)           parents#create
#   new_parent GET    /parents/new(.:format)       parents#new
#  edit_parent GET    /parents/:id/edit(.:format)  parents#edit
#       parent GET    /parents/:id(.:format)       parents#show
#              PATCH  /parents/:id(.:format)       parents#update
#              PUT    /parents/:id(.:format)       parents#update
#     students GET    /students(.:format)          students#index
#              POST   /students(.:format)          students#create
#  new_student GET    /students/new(.:format)      students#new
# edit_student GET    /students/:id/edit(.:format) students#edit
#      student GET    /students/:id(.:format)      students#show
#              PATCH  /students/:id(.:format)      students#update
#              PUT    /students/:id(.:format)      students#update
#      reports GET    /reports(.:format)           reports#index
#              POST   /reports(.:format)           reports#create
#   new_report GET    /reports/new(.:format)       reports#new
#  edit_report GET    /reports/:id/edit(.:format)  reports#edit
#       report GET    /reports/:id(.:format)       reports#show
#              PATCH  /reports/:id(.:format)       reports#update
#              PUT    /reports/:id(.:format)       reports#update
#              DELETE /reports/:id(.:format)       reports#destroy
#              DELETE /students/:id(.:format)      students#destroy
#              DELETE /parents/:id(.:format)       parents#destroy
      # logout DELETE /logout(.:format)            sessions#destroy

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportify</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Reportify</a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          <% if !signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign_up", new_user_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_session_path,class:'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log out", logout_path, method:"delete",class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to current_user.email, root_path,  class:'nav-link'%>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <nav class="bg-light sidebar">
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link" href="/parents">Parents</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/students">Students</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reports">Reports</a>
        </li>
      </ul>
    </nav>

    <div class="wrap">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>